//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSSIRecorder
{
    using System;
    using System.Collections.Generic;
    
    public partial class RSSIRecord
    {
        public int Id { get; set; }
        public string SSID { get; set; }
        public int SignalStrength { get; set; }
        public System.DateTime CreatedOnUtc { get; set; }
    }
}
