//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameDataProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attribute
    {
        public Attribute()
        {
            this.EventAttributes = new HashSet<EventAttribute>();
        }
    
        public int Id { get; set; }
        public string AttributeName { get; set; }
    
        public virtual ICollection<EventAttribute> EventAttributes { get; set; }
    }
}
