//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameDataProject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BalboaConstrictorsEntities : DbContext
    {
        public BalboaConstrictorsEntities()
            : base("name=BalboaConstrictorsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<DataType> DataTypes { get; set; }
        public DbSet<Event> Events { get; set; }
        public DbSet<EventPlayer> EventPlayers { get; set; }
        public DbSet<EventTypeParticipant> EventTypeParticipants { get; set; }
        public DbSet<Player> Players { get; set; }
        public DbSet<PlayerTeam> PlayerTeams { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<Team> Teams { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<UserPlayer> UserPlayers { get; set; }
        public DbSet<PlayerData> PlayerDatas { get; set; }
        public DbSet<Attribute> Attributes { get; set; }
        public DbSet<EventAttribute> EventAttributes { get; set; }
        public DbSet<EventType> EventTypes { get; set; }
        public DbSet<Game> Games { get; set; }
        public DbSet<GameTeam> GameTeams { get; set; }
    }
}
