//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameDataProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public Event()
        {
            this.EventPlayers = new HashSet<EventPlayer>();
        }
    
        public int Id { get; set; }
        public System.DateTime TimeOfEvent { get; set; }
        public int GameId { get; set; }
        public int EventTypeId { get; set; }
    
        public virtual ICollection<EventPlayer> EventPlayers { get; set; }
        public virtual EventType EventType { get; set; }
        public virtual Game Game { get; set; }
    }
}
