//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameDataProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public Game()
        {
            this.Events = new HashSet<Event>();
            this.GameTeams = new HashSet<GameTeam>();
        }
    
        public int Id { get; set; }
        public System.DateTime BeginTime { get; set; }
        public System.DateTime EndTime { get; set; }
    
        public virtual ICollection<Event> Events { get; set; }
        public virtual ICollection<GameTeam> GameTeams { get; set; }
    }
}
