//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameDataProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerData
    {
        public int Id { get; set; }
        public int PlayerId { get; set; }
        public int DataTypeId { get; set; }
        public string TextData { get; set; }
        public Nullable<int> IntegerData { get; set; }
        public Nullable<double> FloatData { get; set; }
        public System.DateTime TimeOfData { get; set; }
    
        public virtual DataType DataType { get; set; }
        public virtual Player Player { get; set; }
    }
}
