//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameDataProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public Player()
        {
            this.EventPlayers = new HashSet<EventPlayer>();
            this.PlayerTeams = new HashSet<PlayerTeam>();
            this.UserPlayers = new HashSet<UserPlayer>();
            this.PlayerDatas = new HashSet<PlayerData>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
    
        public virtual ICollection<EventPlayer> EventPlayers { get; set; }
        public virtual ICollection<PlayerTeam> PlayerTeams { get; set; }
        public virtual ICollection<UserPlayer> UserPlayers { get; set; }
        public virtual ICollection<PlayerData> PlayerDatas { get; set; }
    }
}
